configfile: "config/config.yaml"
import configutil
config = configutil.remap_params(config)

module dengue_acquiredata:
    snakefile:
        config["dengue_acquiredata"]["snakefile"]
    config:
        config["dengue_acquiredata"]["config"]
use rule * from dengue_acquiredata as dengue_acquiredata_*

module dengue_processdenguedata:
    snakefile:
        config["dengue_processdenguedata"]["snakefile"]
    config:
        config["dengue_processdenguedata"]["config"]
use rule * from dengue_processdenguedata as dengue_processdenguedata_*

module dengue_sequencealignment:
    snakefile:
        config["dengue_sequencealignment"]["snakefile"]
    config:
        config["dengue_sequencealignment"]["config"]
use rule * from dengue_sequencealignment as dengue_sequencealignment_*

module dengue_splitgenomeandqc:
    snakefile:
        config["dengue_splitgenomeandqc"]["snakefile"]
    config:
        config["dengue_splitgenomeandqc"]["config"]
use rule * from dengue_splitgenomeandqc as dengue_splitgenomeandqc_*

module dengue_subsample_denv:
    snakefile:
        config["dengue_subsample_denv"]["snakefile"]
    config:
        config["dengue_subsample_denv"]["config"]
use rule * from dengue_subsample_denv as dengue_subsample_denv_*

module dengue_iqtree:
    snakefile:
        config["dengue_iqtree"]["snakefile"]
    config:
        config["dengue_iqtree"]["config"]
use rule * from dengue_iqtree as dengue_iqtree_*

module dengue_treetime:
    snakefile:
        config["dengue_treetime"]["snakefile"]
    config:
        config["dengue_treetime"]["config"]
use rule * from dengue_treetime as dengue_treetime_*

module dengue_mutations:
    snakefile:
        config["dengue_mutations"]["snakefile"]
    config:
        config["dengue_mutations"]["config"]
use rule * from dengue_mutations as dengue_mutations_*

module dengue_translation:
    snakefile:
        config["dengue_translation"]["snakefile"]
    config:
        config["dengue_translation"]["config"]
use rule * from dengue_translation as dengue_translation_*

module dengue_mugration:
    snakefile:
        config["dengue_mugration"]["snakefile"]
    config:
        config["dengue_mugration"]["config"]
use rule * from dengue_mugration as dengue_mugration_*

module dengue_export:
    snakefile:
        config["dengue_export"]["snakefile"]
    config:
        config["dengue_export"]["config"]
use rule * from dengue_export as dengue_export_*
