# Step 6: Treebuilding
configfile: "config/config.yaml"


indir = config["input_namespace"]
outdir = config["output_namespace"]


rule iqtree:
    input:
        aln=f"results/{indir}/subsampled_{{serotype}}.fasta",
    output:
        tree=f"results/{outdir}/subsampled_{{serotype}}.fasta.treefile",
    conda:
        "envs/iqtree.yaml"
    params:
        model="GTR+F+I",
        outdir=f"results/{outdir}",
    log:
        "logs/iqtree_{serotype}.log",
    message:
        "Inferring maximum likelihood phylogenetic trees for using IQ-TREE."
    shell:
        """
        mkdir -p {params.outdir}
        iqtree2 -s {input.aln} -m {params.model} -redo
        mv {input.aln}.* {params.outdir}
        """
