# Step 9: Discrete trait reconstruction
configfile: "config/config.yaml"


indir = config["input_namespace"]
outdir = config["output_namespace"]


rule mugration:
    input:
        time_tree=f"results/{indir['treetime']}/timetree_{{serotype}}.tree",
        metadata=f"results/{indir['subsample']}/subsampled_{{serotype}}_infoTbl.csv",
    output:
        traits=f"results/{outdir}/traits_{{serotype}}.json",
    conda:
        "envs/nextstrain_all.yaml"
    log:
        "logs/mugration_{serotype}.log",
    message:
        "Use Discrete Trait Reconstruction for country and state"
    shell:
        """
        augur traits \
            --tree {input.time_tree} \
            --metadata {input.metadata} \
            --columns Country State \
            --confidence \
            --output {output.traits} > {log} 2>&1
        """


rule _test:
    input:
        f"results/{outdir}/traits_Dengue_1.json",
        f"results/{outdir}/traits_Dengue_2.json",
        f"results/{outdir}/traits_Dengue_3.json",
        f"results/{outdir}/traits_Dengue_4.json",
