name: r_env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - r-base
  - r-optparse
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-ape
  - r-seqinr
  - r-lubridate
  - r-countrycode
  - r-ggplot2
  - r-purrr
