input_namespace:
  fasta: fasta
  metadata: metadata
output_namespace: out
params:
  "Min count": 100
  Target: "Africa"
  Classification: "Major_Lineage"
  "Serotype targets": ["Dengue_1", "Dengue_2", "Dengue_3", "Dengue_4"]
