# Step 1: Acquisition of Genomic Data and Metadata from GenBank
configfile: "config/config.yaml"


outdir = config["output_namespace"]
params = config["params"]


rule acquire_data:
    output:
        zip=f"results/{outdir}/genbank_data.zip",
        metadata=f"results/{outdir}/metadata.tsv",
        fasta=f"results/{outdir}/ncbi_dataset/data/genomic.fna",
    log:
        "logs/acquire_data.log",
    message:
        "Acquiring Genomic Data and Metadata from NCBI database"
    conda:
        "envs/ncbi_datasets_env.yaml"
    params:
        outdir=f"results/{outdir}",
        sequence=params["Sequence"],
        cli=' '.join(params["Command line arguments"]),
        dataformat=params["Data format"]
    shell:
        """
        # Download the data and metadata
        datasets download {params.sequence} \
            --filename {output.zip} &> {log}
        datasets summary {params.sequence} \
            {params.cli} \
            --as-json-lines \
        | dataformat tsv {params.dataformat} > {output.metadata} 2>> {log}
        
        # Unzip the downloaded data
        unzip -d {params.outdir} {output.zip}
        """
