name: Check GRAPEVNE workflow

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "workflows/**"
  push:
    branches:
      - main
    paths:
      - "workflows/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workflows/Dengue/modules/build_local
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pulp==2.7.0 snakemake==7.32
          conda init
          conda activate base
          conda install -n base -c conda-forge mamba
      - name: Test pipeline
        run: |
          ./run.sh
